### ISSUE TITLE
Cleanup mock servers & fix demo

### ISSUE THREAD

**Issue by warpech** [PuppetJs/puppet-polymer-client#20]
After https://github.com/PuppetJs/puppet-polymer-client/pull/16 there are some problems: 

- [x] instances of `jasmine-core` and `jasmine-ajax` still loaded in the test helper, but (probably?) not used anymore
- [x] `demo/index.html` seems to not work anymore (seen on @aloscha's screen)

**Comment by joozek78** [comment]
Live Demo still fails due to dependencies fail

**Comment by joozek78** [comment]
It turned out that iron-component-page is broken. It detects if it's served from gh-pages and if so, it uses cdn.rawgit.com to fetch element to present. It has two problems: 

1. cdn.rawgit.com is case-sensitive and our org name (PuppetJs) contains uppercase characters. Iron-component-page never works in such case (see [code](https://github.com/PolymerElements/iron-component-page/blob/v1.1.6/iron-component-page.html#L535))
1. cdn.rawgit.com caches permanently, but iron-component-page always refers to master, so it quickly grows stale
1. iron-component-page refers to master, but we use gh-pages as main branch

I changed the link in the readme to point directly to demo (which works fine) to avoid iron-component-page

**Comment by warpech** [comment]
@joozek78 could you please write an issue in https://github.com/PolymerElements/iron-component-page about this?

**Comment by joozek78** [comment]
@warpech It seems that there are already 2 issues posted there, both ignored by the team: PolymerElements/iron-component-page#44 and PolymerElements/iron-component-page#101. @tomalec even submitted a PR for the second one, but it hasn't been addressed by the team either. I don't see what I could do there beside "liking" the issues :(

**Comment by warpech** [comment]
I see. Then we we did all we can. Thanks!
