### ISSUE TITLE
Model changes made after a patch sent to server are overwritten by server response

### ISSUE THREAD

**Issue by miyconst** [PuppetJs/puppet-polymer-client#6]
I have the following setup:

```html
<input type="text" value="{{model.Text$::change}}" />
<button type="button" value="{{model.Button$::click}}" onmousedown="++this.value">Click me</button>
```

The input sends patch on change, the button on click. But if you press on the button while input is focused the following occurs:

- Polymer observes change event and updates model.
- `puppet-client` sends patch to server.
- Button's `onmousedown` executes and updates the value to `1`.
- `puppet-client` receives response from server.
- `puppet-client` notifies Polymer about model changes.
- Polymer applies changes and overwrites button's value with `0`.

No click triggered. A gif is included.

![polymer-focus-bug](https://cloud.githubusercontent.com/assets/6435556/13459765/139490ca-e076-11e5-9f56-f1a847c5fc12.gif)

The playground is available: https://github.com/miyconst/Playground/

**Comment by warpech** [comment]
I can reproduce it. 

To reproduce, it is required to hold the mouse button longer than a HTTP request/response time.

**Comment by miyconst** [comment]
Custom `on-click` handler handles click correctly, but the original problem is still there.

```html
<button class="btn btn-primary" on-click="onSubmitClick" disabled="{{model.Submit$}}">Register</button>
```

```js
template.onSubmitClick = function () {
    template.set("model.Submit$", template.model.Submit$ + 1);
};
```

**Comment by warpech** [comment]
This solves the problem for me (event precedence is always `mousedown` -> `mouseup` -> `click`):

`<button type="button" value="{{model.Button$::click}}" onmouseup="++this.value">Click me</button>`

As @miyconst observed:

> It looks like the new puppet-client notifies Polymer like if the entire model was changed.

Yes, indeed this is indeed how it works right now. At the time of notification, I guess that Polymer actually dirty-checks the values, and thinks that `0` in model is more current that the button value, which is `1` already.

I think that the problem comes from in the fact that I am forcing Polymer to use dirty-checking. Dirty-checking does not care about the origin of the change. 

It is very likely that we had this problem before but we didn't notice.

I am experimenting with another way of doing Polymer notifications, which might fix this problem, but it is possible that I will get stuck on it and need to pass it over again to someone else.

**Comment by miyconst** [comment]
@warpech do you think it is a good idea to skip notification if the patch coming from server is empty?

**Comment by warpech** [comment]
> @warpech do you think it is a good idea to skip notification if the patch coming from server is empty?

Good idea!

**Comment by miyconst** [comment]
>Good idea!

I try to always do client side model changes in "Polymer" style, means using `this.set` method instead of changing the actual values.

But we have places where the changes are made directly to the model. So, if we don't notify Polymer about incoming empty patch from server, those changes will never be reflected in UI.

**Comment by miyconst** [comment]
>... those changes will never be reflected in UI

Not correct, the changes will be reflected in UI as soon as a non-empty patch arrives.

**Comment by warpech** [comment]
Fix released in next Starcoutner nightly. Thanks for reporting!
